import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import AppShell from "./components/AppShell";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: [],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`min-h-full flex flex-col font-sans ${inter.className}`}
      >
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
