import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import AppShell from "./components/AppShell";
import "./globals.css";
import { PayPalProviders } from "./paypalProviders";
import { Providers } from "./providers";

const inter = Inter({
  subsets: [],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light h-full antialiased" data-theme="light">
      <body
        className={`min-h-full flex flex-col font-sans ${inter.className}`}
      >
        <PayPalProviders>

          <Providers>
            <AppShell>{children}</AppShell>
          </Providers>
        </PayPalProviders>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
